#pragma config(Sensor, dgtl1,  led1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  led2,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  led3,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  led4,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  led5,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  led6,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  led7,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  led8,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  led9,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, led10,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           steering,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           mainl,         tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port4,           mainr,         tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           flash1,        tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Mecanum Drive - Basic
- This program allows you to remotely control a robot with mecanum wheels.
- The left joystick Y-axis controls the robot's forward and backward movement.
- The left joystick X-axis controls the robot's left and right movement.
- The right joystick X-axis controls the robot's rotation.

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        frontRight          VEX Motor             Front Right motor
Motor Port 3        backRight           VEX Motor             Back Right motor
Motor Port 4        frontLeft           VEX Motor             Front Left motor
Motor Port 5        backLeft            VEX Motor             Back Left motor
----------------------------------------------------------------------------------------------------*/
int steeringTrim=18;
int speed=0;
int profile=1;
int multiplier=3;
string secretCode="";
int secretLength=0;
bool onOff=true;
bool flashset=false;
bool init=true;

void ledSwitch(){
  if(secretLength==1){
    if(onOff==true){
      turnLEDOn(led1);
    }else{
      turnLEDOff(led1);
    }
  }
  if(secretLength==2){
    if(onOff==true){
      turnLEDOn(led2);
    }else{
      turnLEDOff(led2);
    }
  }
  if(secretLength==3){
    if(onOff==true){
      turnLEDOn(led3);
    }else{
      turnLEDOff(led3);
    }
  }
  if(secretLength==4){
    if(onOff==true){
      turnLEDOn(led4);
    }else{
      turnLEDOff(led4);
    }
  }
  if(secretLength==5){
    if(onOff==true){
      turnLEDOn(led5);
    }else{
      turnLEDOff(led5);
    }
  }
  if(secretLength==6){
    if(onOff==true){
      turnLEDOn(led6);
    }else{
      turnLEDOff(led6);
    }
  }
  if(secretLength==7){
    if(onOff==true){
      turnLEDOn(led7);
    }else{
      turnLEDOff(led7);
    }
  }
  if(secretLength==8){
    if(onOff==true){
      turnLEDOn(led8);
    }else{
      turnLEDOff(led8);
    }
  }
  if(secretLength==9){
    if(onOff==true){
      turnLEDOn(led9);
    }else{
      turnLEDOff(led9);
    }
  }
  if(secretLength==10){
    if(onOff==true){
      turnLEDOn(led10);
    }else{
      turnLEDOff(led10);
    }
  }
}

void lightsOff(){
  onOff=false;
  secretLength=10;
  for(secretLength;secretLength>0;secretLength--){
    ledSwitch();
  }
  onOff=true;
}

void nickLed(){
  if(multiplier>=3){
    turnLEDOn(led1);
  }else{
    turnLEDOff(led1);
  }
  if(multiplier>=4){
    turnLEDOn(led2);
  }else{
    turnLEDOff(led2);
  }
  if(multiplier>=5){
    turnLEDOn(led3);
  }else{
    turnLEDOff(led3);
  }
  if(multiplier>=6){
    turnLEDOn(led4);
  }else{
    turnLEDOff(led4);
  }
  if(multiplier>=7){
    turnLEDOn(led5);
  }else{
    turnLEDOff(led5);
  }
  if(multiplier>=8){
    turnLEDOn(led6);
  }else{
    turnLEDOff(led6);
  }
  if(multiplier>=9){
    turnLEDOn(led7);
  }else{
    turnLEDOff(led7);
  }
  if(multiplier>=10){
    turnLEDOn(led8);
  }else{
    turnLEDOff(led8);
  }
}

void flashlight(){
  if(flashset==true){
		turnFlashlightOn(flash1);
	}else{
		turnFlashlightOff(flash1);
	}
	if(vexRT[Btn7U]==1){
  	if(flashset==true){
  		until(vexRT[Btn7U]==0);
   	 flashset=false;
  	}else{
  		until(vexRT[Btn7U]==0);
   		flashset=true;
  	}
  }
}


void trimProg(){
  if(vexRT[Btn7L]==1){
    steeringTrim=steeringTrim-1;
    until(vexRT[Btn7L]!=1);
  }
  if(vexRT[Btn7R]==1){
    steeringTrim=steeringTrim+1;
    until(vexRT[Btn7R]!=1);
  }
}

void profilechange(){
  if(vexRT[Btn8U]==1){
		lightsOff();
    //PlaySoundFile("profile1");
    profile=1;
  }
  if(vexRT[Btn8L]==1){
		lightsOff();
    //PlaySoundFile("profile2");
    profile=2;
  }
  if(vexRT[Btn8D]==1){
		lightsOff();
    //PlaySoundFile("profile3");
    profile=3;
  }
  if(vexRT[Btn8R]==1){
		lightsOff();
    //PlaySoundFile("profile4");
    profile=4;
  }
}

void mainProg(){
while(true){
  //profile Default
  while(profile==1){
    flashlight();
    profilechange();
    trimProg();
    turnLEDOn(led10);
    turnLEDOff(led9);
    turnLEDOff(led8);
    motor[steering] = vexRT[Ch1]+steeringTrim;
    motor[mainl] = speed;
    motor[mainr] = speed;
    if(vexRT[Btn5D]==0&&vexRT[Btn6D]==0){
      speed=vexRT[Ch3]/3;
      }
    if(vexRT[Btn5D]==1||vexRT[Btn6D]==1){
      speed=vexRT[Ch3]/2;
      }
    if(vexRT[Btn5D]==1&&vexRT[Btn6D]==1){
      speed=vexRT[Ch3];
      }
    }
  //profile Nick
  while(profile==2){
    flashlight();
    profilechange();
    trimProg();
    nickLed();
    turnLEDOff(led10);
    turnLEDOn(led9);
    turnLEDOff(led8);
    motor[steering] = vexRT[Ch1]+steeringTrim;
    motor[mainl] = (vexRT[Ch3]/10)*multiplier;
    motor[mainr] = (vexRT[Ch3]/10)*multiplier;
    if(vexRT[Btn5U]==1){
      multiplier=5;
      }
    if(vexRT[Btn5D]==1){
      multiplier=10;
      }
    if(vexRT[Btn6U]==1&&multiplier<10){
      multiplier=multiplier+1;
      until(vexRT[Btn6U]==0);
      }
    if(vexRT[Btn6D]==1&&multiplier>3){
      multiplier=multiplier-1;
      until(vexRT[Btn6D]==0);
      }
    }
  //profile Extra
  while(profile==3){
    flashlight();
    profilechange();
    trimProg();
    turnLEDOff(led10);
    turnLEDOff(led9);
    turnLEDOn(led8);
    motor[steering] = vexRT[Ch1]+steeringTrim;
    motor[mainl] = speed;
    motor[mainr] = speed;
    if(vexRT[Btn5D]==0&&vexRT[Btn6D]==0){
      speed=vexRT[Ch3]/3;
      }
    if(vexRT[Btn5D]==1||vexRT[Btn6D]==1){
      speed=vexRT[Ch3]/2;
      }
    if(vexRT[Btn5D]==1&&vexRT[Btn6D]==1){
      speed=vexRT[Ch3];
      }
    }
  //profile Extra
  while(profile==4){
    flashlight();
    profilechange();
    trimProg();
    turnLEDOn(led10);
    turnLEDOn(led9);
    turnLEDOff(led8);
    motor[steering] = vexRT[Ch1]+steeringTrim;
    motor[mainl] = speed;
    motor[mainr] = speed;
    if(vexRT[Btn5D]==0&&vexRT[Btn6D]==0){
      speed=vexRT[Ch3]/3;
      }
    if(vexRT[Btn5D]==1||vexRT[Btn6D]==1){
      speed=vexRT[Ch3]/2;
      }
    if(vexRT[Btn5D]==1&&vexRT[Btn6D]==1){
      speed=vexRT[Ch3];
      }
    }
  }
}

void unlockCode(){
  while(secretLength<10){
    ledSwitch();
   	if(init==true){
			turnLEDOn(led1);
			turnLEDOn(led2);
			turnLEDOn(led3);
			turnLEDOn(led4);
			turnLEDOn(led5);
			turnLEDOn(led6);
			turnLEDOn(led7);
			turnLEDOn(led8);
			waitInMilliseconds(100);
			turnLEDOff(led1);
			turnLEDOff(led2);
			turnLEDOff(led3);
			turnLEDOff(led4);
			turnLEDOff(led5);
			turnLEDOff(led6);
			turnLEDOff(led7);
			turnLEDOff(led8);
			waitInMilliseconds(100);
		}
    if(vexRT[Btn7U]==1){
    	init=false;
      secretCode=secretCode+"u";
      secretLength=secretLength+1;
      until(vexRT[Btn7U]!=1);
    }
    if(vexRT[Btn7D]==1){
    	init=false;
      secretCode=secretCode+"d";
      secretLength=secretLength+1;
      until(vexRT[Btn7D]!=1);
    }
    if(vexRT[Btn7L]==1){
    	init=false;
      secretCode=secretCode+"l";
      secretLength=secretLength+1;
      until(vexRT[Btn7L]!=1);
    }
    if(vexRT[Btn7R]==1){
    	init=false;
      secretCode=secretCode+"r";
      secretLength=secretLength+1;
      until(vexRT[Btn7R]!=1);
    }
    if(vexRT[Btn8U]==1){
    	init=false;
      secretCode=secretCode+"y";
      secretLength=secretLength+1;
      until(vexRT[Btn8U]!=1);
    }
    if(vexRT[Btn8D]==1){
    	init=false;
      secretCode=secretCode+"b";
      secretLength=secretLength+1;
      until(vexRT[Btn8D]!=1);
    }
    if(vexRT[Btn8L]==1){
    	init=false;
      secretCode=secretCode+"x";
      secretLength=secretLength+1;
      until(vexRT[Btn8L]!=1);
    }
    if(vexRT[Btn8R]==1){
    	init=false;
      secretCode=secretCode+"a";
      secretLength=secretLength+1;
      until(vexRT[Btn8R]!=1);
    }
    if(vexRT[Btn5U]==1||vexRT[Btn5D]==1){
    	init=false;
      secretCode=secretCode+"lb";
      secretLength=secretLength+1;
      until(vexRT[Btn5U]!=1);
    }
    if(vexRT[Btn5D]==1||vexRT[Btn6D]==1){
    	init=false;
      secretCode=secretCode+"rb";
      secretLength=secretLength+1;
      until(vexRT[Btn6U]!=1);
    }
  }
}
task main(){
//PlaySoundFile("unlockcode.wav");
unlockCode();
ledSwitch();
waitInMilliseconds(200);
lightsOff();
for(int time=0;time<4;time++){
	turnLEDOn(led9);
	waitInMilliseconds(300);
	turnLEDOff(led9);
	waitInMilliseconds(300);
}
  if(secretCode=="uuddlrlrba"){
		lightsOff();
    //PlaySoundFile("unlockconfirmed.wav");
		mainProg();
  }else{
    secretCode="";
		lightsOff();
		init=true;
    //PlaySoundFile("accessdenied.wav");
    StartTask(main);
  }
}
